apiVersion: v1
kind: Service
metadata:
    name: "clutser2-558c"
    labels:
        app: "clutser2-558c"
spec:
    type: LoadBalancer
    ports:
    - port: 8069
      targetPort: 8069
      protocol: TCP
      name: http
    selector:
        app: "clutser2-558c"