on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: exquitechprivatereg.azurecr.io
        username: ${{ secrets.acr_exquitechprivatereg_username }}
        password: ${{ secrets.acr_exquitechprivatereg_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t exquitechprivatereg.azurecr.io/clutser2:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push exquitechprivatereg.azurecr.io/clutser2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_clutser2_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep clutser-2bca5 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace clutser-2bca5`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: clutser-2bca5
        container-registry-url: exquitechprivatereg.azurecr.io
        container-registry-username: ${{ secrets.acr_exquitechprivatereg_username }}
        container-registry-password: ${{ secrets.acr_exquitechprivatereg_password }}
        secret-name: clutser2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: clutser-2bca5
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          exquitechprivatereg.azurecr.io/clutser2:${{ github.sha }}
        imagepullsecrets: |
          clutser2dockerauth
